image: maven:latest

stages:
  - build
  - test
  - package
  - deploy
  - run

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test

package:
  stage: package
  script:
    - mvn $MAVEN_CLI_OPTS package
  artifacts:
    paths: [target/demo-app-1.0-jar-with-dependencies.jar]

deploy:
  image: docker:latest
  stage: deploy
  variables:
    DOCKER_DRIVER: overlay
  services:
    - docker:dind
  script:
    - docker build -t demo-app .
    - docker login registry.gitlab.com
    - docker push demo-app

run:
  image: registry.gitlab.com/demo-app
  stage: run
  script:
    - java -jar demo-app-1.0-jar-with-dependencies.jar
